[project]
name = 'stacksforge'
description = 'Create and deploy SIP-010 fungible tokens on Stacks in seconds'
authors = ['AdekunleBamz']
telemetry = false

[contracts.sip-010-trait-ft-standard-v-i2]
path = 'contracts/traits/sip-010-trait-v-i2.clar'
clarity_version = 2
epoch = "2.4"

[contracts.forge-token-v-i2]
path = 'contracts/forge-token-v-i2.clar'
clarity_version = 2
epoch = "2.4"

[contracts.token-factory-v-i2]
path = 'contracts/token-factory-v-i2.clar'
clarity_version = 2
epoch = "2.4"

[[devnet.accounts]]
name = "deployer"
mnemonic = "sell invite acquire kitten bamboo minor property illicit chief smoker beat buddy either axis"
balance = 10000000000

[[devnet.accounts]]
name = "wallet_1"
mnemonic = "sell invite acquire kitten bamboo minor property illicit chief smoker beat buddy either axis"
balance = 1000000000

[devnet]
name = "stacksforge-devnet"
