[network]
name = "simnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong"
balance = 100_000_000_000_000

[accounts.wallet_1]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon cactus"
balance = 100_000_000_000_000

[accounts.wallet_2]
mnemonic = "legal winner thank year wave sausage worth useful legal winner thank yellow"
balance = 100_000_000_000_000

[accounts.wallet_3]
mnemonic = "letter advice cage absurd amount doctor acoustic avoid letter advice cage above"
balance = 100_000_000_000_000
